OrdererOrgs:
  - Name: Orderer
    Domain: carelink.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: CareLink
    Domain: carelink.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
