"""
Transforms hospital-specific DataFrame columns into
CareLink canonical field names using a MappingResult.
"""

from __future__ import annotations

import pandas as pd

from app.models.mapping_result import MappingResult


class CanonicalTransformer:
    """
    Applies a previously generated MappingResult to a DataFrame.

    Mapped columns are renamed to their canonical field names.
    Unmapped source columns are preserved.
    The input DataFrame is never modified in place.
    """

    def transform(
        self,
        dataframe: pd.DataFrame,
        mapping_result: MappingResult,
    ) -> pd.DataFrame:
        """
        Transform source columns into canonical column names.

        Args:
            dataframe: Source dataset.
            mapping_result: Result generated by MappingEngine.

        Returns:
            A new DataFrame containing renamed canonical columns
            and preserved unmapped columns.

        Raises:
            TypeError: If inputs have invalid types.
            ValueError: If multiple source fields map to the same
                canonical field.
        """
        if not isinstance(dataframe, pd.DataFrame):
            raise TypeError("dataframe must be a pandas DataFrame.")

        if not isinstance(mapping_result, MappingResult):
            raise TypeError("mapping_result must be a MappingResult.")

        rename_map: dict[str, str] = {}
        canonical_targets: set[str] = set()

        for mapping in mapping_result.mappings:
            if mapping.source_field not in dataframe.columns:
                raise ValueError(
                    f"Mapped source field '{mapping.source_field}' "
                    "does not exist in the dataframe."
                )

            if mapping.canonical_field in canonical_targets:
                raise ValueError(
                    f"Multiple source fields map to canonical field "
                    f"'{mapping.canonical_field}'."
                )

            rename_map[mapping.source_field] = mapping.canonical_field
            canonical_targets.add(mapping.canonical_field)

        return dataframe.rename(
            columns=rename_map,
            copy=True,
        )
