"""
mapping_engine.py

Orchestrates mapping of hospital-specific dataset schemas
to the CareLink canonical schema.
"""

from __future__ import annotations

from app.mapping.canonical_schema import CANONICAL_FIELDS
from app.mapping.column_matcher import ColumnMatcher
from app.models.mapping_result import MappingResult
from app.models.schema_profile import SchemaProfile


class MappingEngine:
    """
    Maps source dataset fields to CareLink canonical fields.

    The engine delegates individual field matching to ColumnMatcher
    and consolidates the results into a MappingResult.
    """

    def __init__(
        self,
        column_matcher: ColumnMatcher | None = None,
    ) -> None:

        self.column_matcher = (
            column_matcher or ColumnMatcher()
        )

    def map(
        self,
        profile: SchemaProfile,
    ) -> MappingResult:
        """
        Map all source fields in a SchemaProfile to canonical fields.

        Args:
            profile:
                SchemaProfile generated by SchemaAnalyzer.

        Returns:
            MappingResult containing successful mappings,
            unmapped source fields, and missing required fields.
        """

        if not isinstance(profile, SchemaProfile):
            raise TypeError(
                "profile must be a SchemaProfile."
            )

        mappings = []
        unmapped_source_fields = []

        for source_field in profile.columns:

            source_data_type = profile.data_types.get(
                source_field
            )

            mapping = self.column_matcher.match(
                source_field=source_field,
                source_data_type=source_data_type,
            )

            if mapping is None:
                unmapped_source_fields.append(
                    source_field
                )
            else:
                mappings.append(mapping)

        mapped_canonical_fields = {
            mapping.canonical_field
            for mapping in mappings
        }

        missing_required_fields = [
            field.name
            for field in CANONICAL_FIELDS.values()
            if field.required
            and field.name not in mapped_canonical_fields
        ]

        return MappingResult(
            mappings=tuple(mappings),
            unmapped_source_fields=tuple(
                unmapped_source_fields
            ),
            missing_required_fields=tuple(
                missing_required_fields
            ),
        )