"""
schema_fingerprint.py

Generates deterministic fingerprints representing dataset structure.

Unlike the dataset fingerprint generated by Sprint 2, this fingerprint
does not depend on the actual records contained in the dataset.
"""

from __future__ import annotations

import hashlib

from app.models.schema_profile import SchemaProfile


class SchemaFingerprint:
    """
    Generates a deterministic SHA-256 fingerprint for a dataset schema.
    """

    def generate(self, profile: SchemaProfile) -> str:
        """
        Generate a fingerprint from the structural properties of a
        SchemaProfile.

        The fingerprint is based on:

        - column names
        - detected data types

        Column ordering does not affect the resulting fingerprint.

        Dataset values, row count, statistics, and missing-value counts
        are intentionally excluded.

        Args:
            profile:
                SchemaProfile produced by SchemaAnalyzer.

        Returns:
            Hexadecimal SHA-256 schema fingerprint.
        """

        if not isinstance(profile, SchemaProfile):
            raise TypeError(
                "Input must be a SchemaProfile."
            )

        canonical_schema = self._canonicalize(profile)

        return hashlib.sha256(
            canonical_schema.encode("utf-8")
        ).hexdigest()

    @staticmethod
    def _canonicalize(profile: SchemaProfile) -> str:
        """
        Convert schema information into a deterministic representation.

        Each field is represented as:

            column_name:data_type

        Fields are sorted alphabetically so that column ordering in the
        original dataset does not affect the schema fingerprint.
        """

        schema_entries = [
            f"{column}:{profile.data_types[column]}"
            for column in profile.columns
        ]

        schema_entries.sort()

        return "|".join(schema_entries)