"""
schema_detector.py

Determines whether a dataset schema is already known to CareLink.
"""

from __future__ import annotations

from app.mapping.schema_fingerprint import SchemaFingerprint
from app.models.schema import Schema
from app.models.schema_profile import SchemaProfile
from app.registry.schema_registry import SchemaRegistry


class SchemaDetector:
    """
    Detects whether a dataset schema is already registered.

    The detector generates a structural schema fingerprint and uses
    SchemaRegistry as the source of truth for known schemas.
    """

    def __init__(
        self,
        fingerprint_generator: SchemaFingerprint | None = None,
        schema_registry: SchemaRegistry | None = None,
    ) -> None:

        self.fingerprint_generator = (
            fingerprint_generator or SchemaFingerprint()
        )

        self.schema_registry = (
            schema_registry or SchemaRegistry()
        )

    def detect(
        self,
        profile: SchemaProfile,
    ) -> Schema | None:
        """
        Determine whether the supplied schema is already registered.

        Args:
            profile:
                SchemaProfile generated by SchemaAnalyzer.

        Returns:
            The registered Schema if the fingerprint is known,
            otherwise None.
        """

        if not isinstance(profile, SchemaProfile):
            raise TypeError(
                "profile must be a SchemaProfile."
            )

        schema_fingerprint = self.fingerprint(profile)

        return self.schema_registry.get_by_fingerprint(
            schema_fingerprint
        )

    def fingerprint(
        self,
        profile: SchemaProfile,
    ) -> str:
        """
        Generate the structural fingerprint for a SchemaProfile.
        """

        if not isinstance(profile, SchemaProfile):
            raise TypeError(
                "profile must be a SchemaProfile."
            )

        return self.fingerprint_generator.generate(profile)

    def is_known(
        self,
        profile: SchemaProfile,
    ) -> bool:
        """
        Return True when the supplied schema is already registered.
        """

        return self.detect(profile) is not None